# Generated by Django 3.2.16 on 2023-03-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запись удалена')),
                ('autor', models.CharField(max_length=22, verbose_name='Никнейм')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('rubrics', models.CharField(max_length=255, verbose_name='Рубрика')),
                ('preview', models.CharField(max_length=1000, verbose_name='Описание')),
                ('body', models.TextField(verbose_name='Содержание')),
                ('body_as_markdown', models.BooleanField(default=False, verbose_name='Тип Идеи')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
