# Generated by Django 3.2.16 on 2023-03-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запись удалена')),
                ('rating', models.SmallIntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (2, '⭐⭐'), (1, '⭐')], default=5, verbose_name='Рейтинг')),
                ('feedback', models.TextField(default='Без отзыва', verbose_name='Отзыв')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.idea', verbose_name='Идея')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзовы',
            },
        ),
    ]
